### ISSUE TITLE
Syntax error.

### ISSUE THREAD

**Issue by bartrylant** [studioespresso/craft-date-range#19] opened 2020-08-24 08:20 UTC
On Craft 3.5, when trying to edit/create an entry with a date range field, and error page is shown:

Invalid Argument – yii\base\InvalidArgumentException
Syntax error.

```
 in /Users/xxx/Sites/xxx/vendor/studioespresso/craft-date-range/src/fields/data/DateRangeData.php at line 125– yii\helpers\BaseJson::decode('2020-05-06 17:30:00')
119120121122123124125126127128129130131        return false;
    }
 
    public static function normalize($value = null, FieldInterface $config)
    {
        if (!is_array($value)) {
            $value = Json::decode($value);  <<<<<<<<<<<<<<<<<<<<<< ERROR
        }
 
        if ((isset($value['start']['date']) && !$value['start']['date'])
        ) {
            return false;
        } else {
```

**Comment by kerns** [comment] 2020-08-26 08:55
@bartrylant Any fix for this or alternative plugin on your radar?

**Comment by janhenckens** [comment] 2020-08-26 09:48
Hey folks, I'm away on holiday for a few days, sorry for the late reply. I'll try to get online tomorrow to see if I can get a quick fix out. 

@bartrylant could you share the settings you have for the field in question? Thanks!

**Comment by janhenckens** [comment] 2020-08-27 17:12
@bartrylant @kerns Could either of you provide a bit more information on when you are seeing this error? I've tried creating new entries with a date range field and that works without issue on my end. Any extra information would be appreciated, thanks!

**Comment by janhenckens** [comment] 2020-09-07 07:30
@bartrylant @kerns Any more input on this? Ready to help you out but I can't reproduce the issue on my end. Thanks for your feedback!

**Comment by bartrylant** [comment] 2020-09-08 11:39
I've deleted the field and added it again and everything works as it should now. Maybe something went wrong when performing a Craft update from 3.4 to 3.5?

**Closed** 2020-09-17 14:49 UTC
Labels: bug
